# Generated by Django 4.2.11 on 2024-04-15 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Достопримечательность', 'verbose_name_plural': 'Достопримечательности'},
        ),
        migrations.AddField(
            model_name='places',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='places',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг'),
        ),
    ]
